<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- La ruta de salida para cuando lo compiles -->
    <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- Referencia a la API principal del juego -->
    <Reference Include="VintagestoryAPI">
      <HintPath>$(AppData)\Vintagestory\VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    
    <!-- Referencia para el mapa y waypoints -->
    <Reference Include="VSEssentials">
      <HintPath>$(AppData)\Vintagestory\Mods\VSEssentials.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Usamos la misma librería protobuf-net que trae el juego para evitar conflictos de versión -->
    <Reference Include="protobuf-net">
      <HintPath>$(AppData)\Vintagestory\Lib\protobuf-net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net.Core" Condition="Exists('$(AppData)\Vintagestory\Lib\protobuf-net.Core.dll')">
      <HintPath>$(AppData)\Vintagestory\Lib\protobuf-net.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>


